require("plugins.completion")
require("plugins.conform")
require("plugins.mini")
require("plugins.treesitter")
require("plugins.navigation")
require("plugins.ui")
require("plugins.git")
require("plugins.lsp")
